# Add your PostgreSQL database connection string here.
# Example:
# DB_URL = "postgresql://username:password@hostname:5432/database_name"

# Supabase Database Connection
DB_URL = "postgresql://postgres.hvnqenuoyaefojzshvik:NPHwJmpUpMvAO9Mn@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require"
